function R = f(t,y,p)

R = [
     [ (-p(1)*y(1)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) - 2*p(2)*y(2)^2*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(2)*y(2)^2*JAKSTATtest_stimulus(t, 2) - p(3)*y(3)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - p(4)*y(4)) ];
     [ (p(4)*y(4)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(3)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) - 2*p(1)*y(18)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) + 2*p(1)*y(35)*JAKSTATtest_stimulus(t, 1) + 4*p(2)*y(2)^2*JAKSTATtest_stimulus(t, 2) - 8*p(2)*y(2)*y(19)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(20)*JAKSTATtest_stimulus(t, 3) + p(2)*y(2)^2*JAKSTATtest_stimulus(t, 2) + 4*p(2)*y(2)*y(51)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(4)*y(4) - 2*p(4)*y(21) + p(3)*y(3)*JAKSTATtest_stimulus(t, 3) + 2*p(3)*y(66)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(4)*y(4) + 2*p(4)*y(80)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) + 4*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) + 2*p(1)*y(47)*JAKSTATtest_stimulus(t, 1) - 4*p(3)*y(76)*JAKSTATtest_stimulus(t, 3)) ];
     [ (4*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 4*p(3)*y(77)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(3)*JAKSTATtest_stimulus(t, 3) + 2*p(3)*y(78)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (p(1)*y(18)*JAKSTATtest_stimulus(t, 1) - p(1)*y(1)*JAKSTATtest_stimulus(t, 1) - p(1)*y(35)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(35)*JAKSTATtest_stimulus(t, 2)) ];
     [ (2*p(2)*y(2)*y(35)*JAKSTATtest_stimulus(t, 2) - p(3)*y(36)*JAKSTATtest_stimulus(t, 3) - p(1)*y(36)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(3)*y(36)*JAKSTATtest_stimulus(t, 3) - p(1)*y(37)*JAKSTATtest_stimulus(t, 1) - p(4)*y(37)) ];
     [ (p(4)*y(37) - p(1)*y(38)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(39)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(40)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(41)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(42)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(43)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(44)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(45)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(46)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(1)*y(18)*JAKSTATtest_stimulus(t, 1) - p(1)*y(1)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(36)*JAKSTATtest_stimulus(t, 3) - p(1)*y(47)*JAKSTATtest_stimulus(t, 1)) ];
     [ (- 2*p(3)*y(36)*JAKSTATtest_stimulus(t, 3) - p(1)*y(48)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(3)*y(36)*JAKSTATtest_stimulus(t, 3) - p(1)*y(49)*JAKSTATtest_stimulus(t, 1)) ];
     [ (-p(1)*y(50)*JAKSTATtest_stimulus(t, 1)) ];
     [ (p(1)*y(36)*JAKSTATtest_stimulus(t, 1) - p(3)*y(51)*JAKSTATtest_stimulus(t, 3) - 2*p(2)*y(2)^2*JAKSTATtest_stimulus(t, 2) + 2*p(2)*y(2)*y(19)*JAKSTATtest_stimulus(t, 2) - 4*p(2)*y(2)*y(51)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(37)*JAKSTATtest_stimulus(t, 1) - p(4)*y(52) + p(3)*y(51)*JAKSTATtest_stimulus(t, 3) - 4*p(2)*y(2)*y(52)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(4)*y(52) + p(1)*y(38)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(53)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(39)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(54)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(40)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(55)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(41)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(56)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(42)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(57)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(43)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(58)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(44)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(59)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(45)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(60)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(46)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(61)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(1)*JAKSTATtest_stimulus(t, 1) + p(1)*y(35)*JAKSTATtest_stimulus(t, 1) + p(1)*y(47)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(51)*JAKSTATtest_stimulus(t, 3) - 4*p(2)*y(2)*y(62)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(48)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(51)*JAKSTATtest_stimulus(t, 3) - 4*p(2)*y(2)*y(63)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(49)*JAKSTATtest_stimulus(t, 1) + p(3)*y(51)*JAKSTATtest_stimulus(t, 3) - 4*p(2)*y(2)*y(64)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(1)*y(50)*JAKSTATtest_stimulus(t, 1) - 4*p(2)*y(2)*y(65)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(3)*y(20)*JAKSTATtest_stimulus(t, 3) - p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - p(4)*y(66) - p(3)*y(66)*JAKSTATtest_stimulus(t, 3) + 2*p(2)*y(2)*y(52)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(4)*y(66) - p(3)*y(67)*JAKSTATtest_stimulus(t, 3) + 2*p(2)*y(2)*y(53)*JAKSTATtest_stimulus(t, 2)) ];
     [ (2*p(2)*y(2)*y(54)*JAKSTATtest_stimulus(t, 2) - p(3)*y(68)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(55)*JAKSTATtest_stimulus(t, 2) - p(3)*y(69)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(56)*JAKSTATtest_stimulus(t, 2) - p(3)*y(70)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(57)*JAKSTATtest_stimulus(t, 2) - p(3)*y(71)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(58)*JAKSTATtest_stimulus(t, 2) - p(3)*y(72)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(59)*JAKSTATtest_stimulus(t, 2) - p(3)*y(73)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(60)*JAKSTATtest_stimulus(t, 2) - p(3)*y(74)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(2)*y(2)*y(61)*JAKSTATtest_stimulus(t, 2) - p(3)*y(75)*JAKSTATtest_stimulus(t, 3)) ];
     [ (2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(20)*JAKSTATtest_stimulus(t, 3) + p(1)*y(36)*JAKSTATtest_stimulus(t, 1) - p(3)*y(76)*JAKSTATtest_stimulus(t, 3) + 2*p(2)*y(2)*y(62)*JAKSTATtest_stimulus(t, 2)) ];
     [ (2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(20)*JAKSTATtest_stimulus(t, 3) - p(3)*y(77)*JAKSTATtest_stimulus(t, 3) + 2*p(2)*y(2)*y(63)*JAKSTATtest_stimulus(t, 2)) ];
     [ (p(3)*y(20)*JAKSTATtest_stimulus(t, 3) - p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - p(3)*y(78)*JAKSTATtest_stimulus(t, 3) + 2*p(2)*y(2)*y(64)*JAKSTATtest_stimulus(t, 2)) ];
     [ (2*p(2)*y(2)*y(65)*JAKSTATtest_stimulus(t, 2) - p(3)*y(79)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(4)*y(21) - p(4)*y(4) - p(4)*y(80) + p(3)*y(67)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(68)*JAKSTATtest_stimulus(t, 3) - p(4)*y(81)) ];
     [ (p(3)*y(69)*JAKSTATtest_stimulus(t, 3) - p(4)*y(82)) ];
     [ (p(3)*y(70)*JAKSTATtest_stimulus(t, 3) - p(4)*y(83)) ];
     [ (p(3)*y(71)*JAKSTATtest_stimulus(t, 3) - p(4)*y(84)) ];
     [ (p(3)*y(72)*JAKSTATtest_stimulus(t, 3) - p(4)*y(85)) ];
     [ (p(3)*y(73)*JAKSTATtest_stimulus(t, 3) - p(4)*y(86)) ];
     [ (p(3)*y(74)*JAKSTATtest_stimulus(t, 3) - p(4)*y(87)) ];
     [ (p(3)*y(75)*JAKSTATtest_stimulus(t, 3) - p(4)*y(88)) ];
     [ (p(1)*y(37)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - p(4)*y(89) - 2*p(3)*y(66)*JAKSTATtest_stimulus(t, 3) + p(3)*y(76)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(77)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(66)*JAKSTATtest_stimulus(t, 3) - p(4)*y(90)) ];
     [ (p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - p(4)*y(91) + p(3)*y(66)*JAKSTATtest_stimulus(t, 3) + p(3)*y(78)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(79)*JAKSTATtest_stimulus(t, 3) - p(4)*y(92)) ];
     [ (p(4)*y(81)) ];
     [ (p(4)*y(82)) ];
     [ (p(4)*y(83)) ];
     [ (p(4)*y(84)) ];
     [ (p(4)*y(85)) ];
     [ (p(4)*y(86)) ];
     [ (p(4)*y(87)) ];
     [ (p(4)*y(88)) ];
     [ (p(4)*y(89) + p(1)*y(38)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(67)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(4)*y(90) - 2*p(3)*y(67)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(4)*y(91) + p(3)*y(67)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(4)*y(92)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(39)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(68)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(68)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(68)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(40)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(69)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(69)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(69)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(41)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(70)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(70)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(70)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(42)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(71)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(71)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(71)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(43)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(72)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(72)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(72)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(44)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(73)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(73)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(73)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (0) ];
     [ (p(1)*y(45)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(74)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(74)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(74)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (p(1)*y(46)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(75)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(75)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(75)*JAKSTATtest_stimulus(t, 3)) ];
     [ (0) ];
     [ (4*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) + p(1)*y(48)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(76)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(77)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(1)*y(49)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) + p(3)*y(76)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(78)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(1)*y(50)*JAKSTATtest_stimulus(t, 1) - 2*p(3)*y(79)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(77)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(3)*JAKSTATtest_stimulus(t, 3) - 2*p(3)*y(78)*JAKSTATtest_stimulus(t, 3)) ];
     [ (-2*p(3)*y(79)*JAKSTATtest_stimulus(t, 3)) ];
     [ (p(3)*y(79)*JAKSTATtest_stimulus(t, 3)) ];
];
